# Dans HELM, les mdps sont récupérés avec envFrom
# Les noms des variables doivent coîncider avec la conf de Postgres et Pgadmin
# Sinon erreur :
# You need to define the PGADMIN_DEFAULT_EMAIL and PGADMIN_DEFAULT_PASSWORD or PGADMIN_DEFAULT_PASSWORD_FILE environment variables.

apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  POSTGRES_USER: "admin"
  POSTGRES_DB: "storedb"
  POSTGRES_HOST_AUTH_METHOD: "trust"
  PGADMIN_DEFAULT_EMAIL: "gp.engineering@pm.me"
---

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  PGADMIN_DEFAULT_PASSWORD: cm9vdA==