apiVersion: v1
kind: ConfigMap
metadata:
  name: cast-db-configmap
data:
  POSTGRES_USER: "cast_db_username"
  POSTGRES_DB: "cast_db_dev"
  POSTGRES_HOST_AUTH_METHOD: "trust"
  
---

apiVersion: v1
kind: Secret
metadata:
  name: cast-db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: bW92aWVfZGJfcGFzc3dvcmQ=

---
  
apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-db-configmap
data:
  POSTGRES_USER: "movie_db_username"
  POSTGRES_DB: "movie_db_dev"
  POSTGRES_HOST_AUTH_METHOD: "trust"
  
---

apiVersion: v1
kind: Secret
metadata:
  name: movie-db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: Y2FzdF9kYl9wYXNzd29yZA==