apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.cast_db.name }}
  labels:
    name : {{.Values.cast_db.name }}
spec:
  replicas: {{ .Values.cast_db.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.cast_db.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.cast_db.name }}
    spec:
      containers:
        - name: {{ .Values.cast_db.name }}
          env:
          - name: POSTGRES_USER
            value: "cast_db_username"
          - name: POSTGRES_DB
            value: "cast_db_dev"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: "trust"
          image: {{ .Values.cast_db.image }}
          ports:
            - containerPort: {{ .Values.cast_db.service.port }}
              protocol: TCP
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.movie_db.name }}
  labels:
    name : {{.Values.movie_db.name }}
spec:
  replicas: {{ .Values.movie_db.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.movie_db.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.movie_db.name }}
    spec:
      containers:
        - name: {{ .Values.movie_db.name }}
          env:
            - name: POSTGRES_USER
              value: "movie_db_username"
            - name: POSTGRES_DB
              value: "movie_db_dev"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
          # envFrom:
          #   - secretRef:
          #       name: {{ .Values.movie_db.config.secret }}
          #   - configMapRef:
          #       name: {{ .Values.movie_db.config.configmap }}
          image: {{ .Values.movie_db.image }}
          ports:
            - containerPort: {{ .Values.movie_db.service.port }}
              protocol: TCP
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
